#pragma config(Sensor, port4,  3,              sensorVexIQ_Color12Color)
#pragma config(Sensor, port7,  ru,             sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          b,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          a,             tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
  nMotorEncoder[a] = 0;
  nMotorEncoder[b] = 0;
  motor[a]=100;
  if (nMotorEncoder[a] == 360);
  motor[a]=0;


}
