#pragma config(Sensor, port4,  3,              sensorVexIQ_Color12Color)
#pragma config(Sensor, port7,  ru,             sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          b,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          a,             tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 //int nMotorEncoder[motor6] = 0;
 //int nMotorEncoder[motor1] = 0;
 //abs(nMotorEncoder[motor1]) = 100;
// abs(nMotorEncoder[motor6]) = 100;
 motor[b] = -50;
 motor[a] = 50;
 wait1Msec(100000);

}
