#pragma config(Motor,  motor1,          a,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          motor2,        tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor10,         motor4,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         motor3,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motor3] = -50;
	wait1Msec(200);
  motor[a] = 50;
  motor[motor2] = 0;
  wait1Msec(500);
  motor[a] = 50;
  motor[motor2] = -50;
  wait1Msec(800);
  motor[a] = 0;
  motor[motor2] = 0;
  wait1Msec(1000);
  motor[motor3] = 50;
  wait1Msec(1000);
  motor[motor3] = 0;
  wait1Msec(200);
  motor[motor4] = 127;
  wait1Msec(500);
  motor[motor4] = 0;
  wait1Msec(100);
  motor[motor3] = 50;
  wait1Msec(2000);

  motor[motor2] = 50;
  motor[a] = -50;
  wait1Msec(1000);
  motor[motor2] = 0;
  motor[a] = 0;
  wait1Msec(1000);
  motor[motor2] = 30;
  motor[a] = 30;
  wait1Msec(200);
  motor[motor2] = 0;
  motor[a] = 0;
  wait1Msec(200);
  motor[motor3] = -50;
  wait1Msec(1000);
  motor[motor3] = 0;
  wait1Msec(1000);
  motor[motor2] = -50;
  motor[a] = -50;
  wait1Msec(1000);

  motor[motor2] = 0;
  motor[a] = 0;
  wait1Msec(200);


  motor[motor3] = 50;
	wait1Msec(500);



  motor[motor4] = -60;
  wait1Msec(300);

  motor[motor4] = 0;
  wait1Msec(500);

	motor[motor3] = 50;
	wait1Msec(500);

  motor[a] = 50;
  motor[motor2] = -50;
  wait1Msec(700);

  motor[a] = 0;
  motor[motor2] = 0;
  wait1Msec(100);

  motor[a] = 50;
  motor[motor2] = 50;
  wait1Msec(4900);

  motor[a] = 0;
  motor[motor2] = 0;
  wait1Msec(100);

  motor[motor3] = -100;
	wait1Msec(1000);

	motor[motor3] = 0;
	wait1Msec(200);

  motor[a] = -50;
  motor[motor2] = 50;
  wait1Msec(1700);

  motor[a] = 0;
  motor[motor2] = 0;
  wait1Msec(100);

  motor[a] = 50;
  motor[motor2] = 50;
  wait1Msec(9000);

  motor[a] = 0;
  motor[motor2] = 0;
  wait1Msec(100);

  motor[motor3] = 50;
	wait1Msec(1000);

	 motor[motor3] = 0;
	wait1Msec(200);

	motor[a] = -50;
  motor[motor2] = -50;
  wait1Msec(2000);

  motor[a] = 0;
  motor[motor2] = 0;
  wait1Msec(500);
}
